# Generated by Django 2.2.1 on 2019-08-12 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edit_app', '0002_auto_20190812_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='name',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
    ]
