# Generated by Django 2.2.1 on 2019-08-12 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edit_app', '0003_task_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='abstract',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='resources',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='solution_abstract',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_abstract',
            field=models.TextField(blank=True),
        ),
    ]
