# Generated by Django 2.2.1 on 2019-08-12 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edit_app', '0005_auto_20190812_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='edit_app.Skill'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='prerequisites',
            field=models.ManyToManyField(blank=True, related_name='applications', to='edit_app.Skill'),
        ),
    ]
