# Generated by Django 2.2.1 on 2019-08-14 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edit_app', '0006_auto_20190812_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='path',
            field=models.CharField(blank=True, max_length=4096),
        ),
        migrations.AlterField(
            model_name='task',
            name='source',
            field=models.CharField(blank=True, max_length=4096),
        ),
    ]
