# Generated by Django 2.2.1 on 2019-08-14 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edit_app', '0009_auto_20190814_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='status',
            field=models.CharField(choices=[('green', 'Validated'), ('orange', 'Waiting for validation'), ('red', 'Todo')], default='red', max_length=5),
        ),
    ]
