# Generated by Django 2.2.1 on 2019-08-15 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edit_app', '0012_auto_20190814_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='difficulty',
            field=models.IntegerField(choices=[(0, 'Nothing new to find'), (1, 'Needs minutes to find'), (2, 'Needs hours to find'), (3, 'Hard to find by yourself')], default=0),
        ),
    ]
