# Generated by Django 2.2.1 on 2019-08-15 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edit_app', '0013_skill_difficulty'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='comments',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('blue', 'Validated'), ('orange', 'Waiting for validation'), ('red', 'Todo')], default='red', max_length=7),
        ),
    ]
