# Generated by Django 2.2.1 on 2019-08-15 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edit_app', '0014_auto_20190815_0821'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='difficulty',
            field=models.IntegerField(choices=[(0, 'Nothing new to find'), (1, 'Needs minutes to find'), (2, 'Needs hours to find'), (3, 'Hard to find by yourself')], default=0),
        ),
    ]
