# Generated by Django 2.2.1 on 2019-08-15 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edit_app', '0015_task_difficulty'),
    ]

    operations = [
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
        ),
    ]
